services:
  postgres:
    image: postgres:16
    container_name: camila-modas-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: camila_modas
      POSTGRES_USER: camila
      POSTGRES_PASSWORD: camila
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: camila-modas-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres-data:
